runtime: python
api_version: 1
env: flex
entrypoint: gunicorn -b :$PORT main:app
threadsafe: true
service: extract
handlers:
- url: /static
  static_dir: static
- url: /.*
  script: main.app

runtime_config:
    python_version: 2
#[START env]
env_variables:
    PUBSUB_TOPIC: your-topic
    # This token is used to verify that requests originate from your
    # application. It can be any sufficiently random string.
    PUBSUB_VERIFICATION_TOKEN: 1234abc
#[END env]